apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::078427121643:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-13VK909TUBFXO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::078427121643:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-29T09:58:19Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1644"
  uid: 3c2c2833-2944-4a47-bddf-e97a22cdc47a
